function out = model
%
% ddl0.m
%
% Model exported on Oct 8 2025, 19:09 by COMSOL 6.2.0.290.

import com.comsol.model.*
import com.comsol.model.util.*

model = ModelUtil.create('Model');

model.modelPath('/Users/howardtu/Documents/modeling/continuum/feecm/comsol/ddl');

model.label('ddl0.mph');

model.title('Diffuse Double Layer');

model.description(['This example is an extension of the Diffuse Double Layer model and demonstrates how to incorporate charge transfer in a diffuse double layer described by the coupled Nernst' native2unicode(hex2dec({'20' '13'}), 'unicode') 'Planck' native2unicode(hex2dec({'20' '13'}), 'unicode') 'Poisson set of equations.']);

model.param.set('T0', '25[degC]', 'Temperature');
model.param.set('V_therm', 'R_const*T0/F_const', 'Thermal voltage');
model.param.set('DA', '1e-12[m^2/s]', 'Diffusion coefficient, cation');
model.param.set('DX', 'DA/5', 'Diffusion coefficient, anion');
model.param.set('cA_bulk', '110[mol/m^3]', 'Bulk cation concentration');
model.param.set('cX_bulk', 'cA_bulk', 'Bulk anion concentration');
model.param.set('zA', '+1', 'Cation charge');
model.param.set('zX', '-1', 'Anion charge');
model.param.set('Istr_bulk', '0.5*((zA^2+zX^2)*cA_bulk)', 'Bulk ionic strength');
model.param.set('eps_PEO', '5.0', 'Relative permittivity of PEO electrolyte');
model.param.set('xD', 'sqrt(epsilon0_const*eps_H2O*V_therm/(2*F_const*Istr_bulk))', 'Debye length');
model.param.set('xS', '0.2[nm]', 'Stern layer thickness');
model.param.set('L_cell', 'xD*10', 'Cell length');
model.param.set('h_max', 'L_cell/20', 'Maximum mesh element size');
model.param.set('h_max_surf', 'xD/100', 'Maximum mesh element size (electrode)');
model.param.set('Cd_GCS', 'epsilon0_const/(xD/eps_H2O+xS/eps_S)', 'Capacitance per unit area (GCS theory, low potential limit)');
model.param.set('phiM', '1[mV]', 'Voltage of electrode vs PZC');
model.param.set('eps_S', '10', 'Relative permittivity of Stern layer');

model.component.create('comp1', true);

model.component('comp1').geom.create('geom1', 1);

model.component('comp1').mesh.create('mesh1');

model.component('comp1').geom('geom1').create('i1', 'Interval');
model.component('comp1').geom('geom1').feature('i1').set('coord', {'0' 'L_cell'});
model.component('comp1').geom('geom1').run;

model.component('comp1').variable.create('var1');
model.component('comp1').variable('var1').set('deltaphi', 'phiM-phi', 'Electrode-OHP potential difference');
model.component('comp1').variable('var1').set('rho_surf', 'epsilon0_const*eps_S*deltaphi/xS', 'Surface charge density');

model.component('comp1').physics.create('es', 'Electrostatics', 'geom1');
model.component('comp1').physics('es').field('electricpotential').field('phi');
model.component('comp1').physics('es').create('sfcd1', 'SurfaceChargeDensity', 0);
model.component('comp1').physics('es').feature('sfcd1').selection.set([1]);
model.component('comp1').physics('es').create('gnd1', 'Ground', 0);
model.component('comp1').physics('es').feature('gnd1').selection.set([2]);
model.component('comp1').physics.create('tds', 'DilutedSpecies', 'geom1');
model.component('comp1').physics('tds').field('concentration').field('cA');
model.component('comp1').physics('tds').field('concentration').component({'cA' 'cX'});
model.component('comp1').physics('tds').create('conc1', 'Concentration', 0);
model.component('comp1').physics('tds').feature('conc1').selection.set([2]);

model.component('comp1').multiphysics.create('pc1', 'PotentialCoupling', 1);
model.component('comp1').multiphysics('pc1').selection.all;
model.component('comp1').multiphysics.create('scdc1', 'SpaceChargeDensityCoupling', 1);
model.component('comp1').multiphysics('scdc1').selection.all;

model.component('comp1').mesh('mesh1').create('edg1', 'Edge');
model.component('comp1').mesh('mesh1').feature('edg1').create('size1', 'Size');
model.component('comp1').mesh('mesh1').feature('edg1').create('size2', 'Size');
model.component('comp1').mesh('mesh1').feature('edg1').feature('size2').selection.geom('geom1', 0);
model.component('comp1').mesh('mesh1').feature('edg1').feature('size2').selection.set([1]);

model.component('comp1').view('view1').axis.set('xmin', -1.5210268600185373E-9);
model.component('comp1').view('view1').axis.set('xmax', 3.194159603481239E-8);

model.common('cminpt').set('modified', {'temperature' 'T0'});

model.component('comp1').physics('es').feature('ccn1').set('epsilonr_mat', 'userdef');
model.component('comp1').physics('es').feature('ccn1').set('epsilonr', {'eps_H2O'; '0'; '0'; '0'; 'eps_H2O'; '0'; '0'; '0'; 'eps_H2O'});
model.component('comp1').physics('es').feature('sfcd1').set('rhoqs', 'rho_surf');
model.component('comp1').physics('tds').prop('ShapeProperty').set('order_concentration', 2);
model.component('comp1').physics('tds').prop('TransportMechanism').set('Convection', false);
model.component('comp1').physics('tds').prop('TransportMechanism').set('Migration', true);
model.component('comp1').physics('tds').feature('sp1').set('z', {'zA'; 'zX'});
model.component('comp1').physics('tds').feature('cdm1').set('D_cA', {'DA'; '0'; '0'; '0'; 'DA'; '0'; '0'; '0'; 'DA'});
model.component('comp1').physics('tds').feature('cdm1').set('D_cX', {'DX'; '0'; '0'; '0'; 'DX'; '0'; '0'; '0'; 'DX'});
model.component('comp1').physics('tds').feature('init1').set('initc', {'cA_bulk'; 'cX_bulk'});
model.component('comp1').physics('tds').feature('conc1').set('species', [1; 1]);
model.component('comp1').physics('tds').feature('conc1').set('c0', {'cA_bulk'; 'cX_bulk'});

model.component('comp1').mesh('mesh1').feature('edg1').feature('size1').set('custom', 'on');
model.component('comp1').mesh('mesh1').feature('edg1').feature('size1').set('hmax', 'h_max');
model.component('comp1').mesh('mesh1').feature('edg1').feature('size1').set('hmaxactive', true);
model.component('comp1').mesh('mesh1').feature('edg1').feature('size1').set('hmin', 9.13E-12);
model.component('comp1').mesh('mesh1').feature('edg1').feature('size1').set('hminactive', false);
model.component('comp1').mesh('mesh1').feature('edg1').feature('size2').set('custom', 'on');
model.component('comp1').mesh('mesh1').feature('edg1').feature('size2').set('hmax', 'h_max_surf');
model.component('comp1').mesh('mesh1').feature('edg1').feature('size2').set('hmaxactive', true);
model.component('comp1').mesh('mesh1').feature('edg1').feature('size2').set('hmin', 9.13E-12);
model.component('comp1').mesh('mesh1').feature('edg1').feature('size2').set('hminactive', false);
model.component('comp1').mesh('mesh1').run;

model.study.create('std1');
model.study('std1').create('stat', 'Stationary');
model.study('std1').create('time', 'Transient');

model.sol.create('sol1');
model.sol('sol1').study('std1');
model.sol('sol1').attach('std1');
model.sol('sol1').create('st1', 'StudyStep');
model.sol('sol1').create('v1', 'Variables');
model.sol('sol1').create('s1', 'Stationary');
model.sol('sol1').create('su1', 'StoreSolution');
model.sol('sol1').create('st2', 'StudyStep');
model.sol('sol1').create('v2', 'Variables');
model.sol('sol1').create('t1', 'Time');
model.sol('sol1').feature('s1').create('p1', 'Parametric');
model.sol('sol1').feature('s1').create('fc1', 'FullyCoupled');
model.sol('sol1').feature('s1').create('d1', 'Direct');
model.sol('sol1').feature('s1').create('i1', 'Iterative');
model.sol('sol1').feature('s1').feature('i1').create('mg1', 'Multigrid');
model.sol('sol1').feature('s1').feature('i1').feature('mg1').feature('pr').create('sl1', 'SORLine');
model.sol('sol1').feature('s1').feature('i1').feature('mg1').feature('po').create('sl1', 'SORLine');
model.sol('sol1').feature('s1').feature('i1').feature('mg1').feature('cs').create('d1', 'Direct');
model.sol('sol1').feature('s1').feature.remove('fcDef');
model.sol('sol1').feature('t1').create('fc1', 'FullyCoupled');
model.sol('sol1').feature('t1').create('d1', 'Direct');
model.sol('sol1').feature('t1').create('i1', 'Iterative');
model.sol('sol1').feature('t1').feature('i1').create('mg1', 'Multigrid');
model.sol('sol1').feature('t1').feature('i1').feature('mg1').feature('pr').create('sl1', 'SORLine');
model.sol('sol1').feature('t1').feature('i1').feature('mg1').feature('po').create('sl1', 'SORLine');
model.sol('sol1').feature('t1').feature('i1').feature('mg1').feature('cs').create('d1', 'Direct');
model.sol('sol1').feature('t1').feature.remove('fcDef');

model.result.create('pg1', 'PlotGroup1D');
model.result.create('pg2', 'PlotGroup1D');
model.result.create('pg3', 'PlotGroup1D');
model.result.create('pg4', 'PlotGroup1D');
model.result.create('pg5', 'PlotGroup1D');
model.result('pg1').create('lngr1', 'LineGraph');
model.result('pg1').create('ptgr1', 'PointGraph');
model.result('pg1').feature('lngr1').set('xdata', 'expr');
model.result('pg1').feature('lngr1').selection.set([1]);
model.result('pg1').feature('ptgr1').selection.set([1]);
model.result('pg1').feature('ptgr1').set('expr', 'phiM');
model.result('pg2').create('lngr1', 'LineGraph');
model.result('pg2').create('lngr2', 'LineGraph');
model.result('pg2').feature('lngr1').set('xdata', 'expr');
model.result('pg2').feature('lngr1').selection.set([1]);
model.result('pg2').feature('lngr1').set('expr', 'cA');
model.result('pg2').feature('lngr2').set('xdata', 'expr');
model.result('pg2').feature('lngr2').selection.set([1]);
model.result('pg2').feature('lngr2').set('expr', 'cX');
model.result('pg3').create('lngr1', 'LineGraph');
model.result('pg3').feature('lngr1').set('xdata', 'expr');
model.result('pg3').feature('lngr1').selection.set([1]);
model.result('pg3').feature('lngr1').set('expr', 'cA');
model.result('pg3').feature('lngr1').create('col1', 'Color');
model.result('pg3').feature('lngr1').feature('col1').set('expr', 'phiM');
model.result('pg4').create('lngr1', 'LineGraph');
model.result('pg4').feature('lngr1').set('xdata', 'expr');
model.result('pg4').feature('lngr1').selection.set([1]);
model.result('pg4').feature('lngr1').set('expr', 'cX');
model.result('pg4').feature('lngr1').create('col1', 'Color');
model.result('pg4').feature('lngr1').feature('col1').set('expr', 'phiM');
model.result('pg5').create('ptgr1', 'PointGraph');
model.result('pg5').create('glob1', 'Global');
model.result('pg5').feature('ptgr1').selection.set([1]);
model.result('pg5').feature('ptgr1').set('expr', 'rho_surf');

model.study('std1').feature('stat').active(false);
model.study('std1').feature('stat').set('useparam', true);
model.study('std1').feature('stat').set('pname', {'phiM'});
model.study('std1').feature('stat').set('plistarr', {'range(1,1,10)'});
model.study('std1').feature('stat').set('punit', {'mV'});
model.study('std1').feature('time').set('tunit', 'ms');
model.study('std1').feature('time').set('tlist', '10^{range(log10(0.001),1/3,log10(10))}');

model.sol('sol1').attach('std1');
model.sol('sol1').feature('st1').label('Compile Equations: Stationary');
model.sol('sol1').feature('v1').label('Dependent Variables 1.1');
model.sol('sol1').feature('s1').label('Stationary Solver 1.1');
model.sol('sol1').feature('s1').set('probesel', 'none');
model.sol('sol1').feature('s1').feature('dDef').label('Direct 2');
model.sol('sol1').feature('s1').feature('aDef').label('Advanced 1');
model.sol('sol1').feature('s1').feature('aDef').set('cachepattern', true);
model.sol('sol1').feature('s1').feature('p1').label('Parametric 1.1');
model.sol('sol1').feature('s1').feature('p1').set('pname', {'phiM'});
model.sol('sol1').feature('s1').feature('p1').set('plistarr', {'range(1,1,10)'});
model.sol('sol1').feature('s1').feature('p1').set('punit', {'mV'});
model.sol('sol1').feature('s1').feature('fc1').label('Fully Coupled 1.1');
model.sol('sol1').feature('s1').feature('fc1').set('linsolver', 'd1');
model.sol('sol1').feature('s1').feature('fc1').set('initstep', 0.01);
model.sol('sol1').feature('s1').feature('fc1').set('minstep', 1.0E-6);
model.sol('sol1').feature('s1').feature('fc1').set('maxiter', 50);
model.sol('sol1').feature('s1').feature('d1').label('Direct (Merged)');
model.sol('sol1').feature('s1').feature('i1').label('AMG, concentrations (tds)');
model.sol('sol1').feature('s1').feature('i1').set('nlinnormuse', true);
model.sol('sol1').feature('s1').feature('i1').set('maxlinit', 1000);
model.sol('sol1').feature('s1').feature('i1').feature('ilDef').label('Incomplete LU 1');
model.sol('sol1').feature('s1').feature('i1').feature('mg1').label('Multigrid 1.1');
model.sol('sol1').feature('s1').feature('i1').feature('mg1').set('prefun', 'saamg');
model.sol('sol1').feature('s1').feature('i1').feature('mg1').set('maxcoarsedof', 50000);
model.sol('sol1').feature('s1').feature('i1').feature('mg1').set('saamgcompwise', true);
model.sol('sol1').feature('s1').feature('i1').feature('mg1').set('usesmooth', false);
model.sol('sol1').feature('s1').feature('i1').feature('mg1').feature('pr').label('Presmoother 1');
model.sol('sol1').feature('s1').feature('i1').feature('mg1').feature('pr').feature('soDef').label('SOR 1');
model.sol('sol1').feature('s1').feature('i1').feature('mg1').feature('pr').feature('sl1').label('SOR Line 1.1');
model.sol('sol1').feature('s1').feature('i1').feature('mg1').feature('pr').feature('sl1').set('linesweeptype', 'ssor');
model.sol('sol1').feature('s1').feature('i1').feature('mg1').feature('pr').feature('sl1').set('iter', 1);
model.sol('sol1').feature('s1').feature('i1').feature('mg1').feature('pr').feature('sl1').set('linerelax', 0.7);
model.sol('sol1').feature('s1').feature('i1').feature('mg1').feature('pr').feature('sl1').set('relax', 0.5);
model.sol('sol1').feature('s1').feature('i1').feature('mg1').feature('po').label('Postsmoother 1');
model.sol('sol1').feature('s1').feature('i1').feature('mg1').feature('po').feature('soDef').label('SOR 1');
model.sol('sol1').feature('s1').feature('i1').feature('mg1').feature('po').feature('sl1').label('SOR Line 1.1');
model.sol('sol1').feature('s1').feature('i1').feature('mg1').feature('po').feature('sl1').set('linesweeptype', 'ssor');
model.sol('sol1').feature('s1').feature('i1').feature('mg1').feature('po').feature('sl1').set('iter', 1);
model.sol('sol1').feature('s1').feature('i1').feature('mg1').feature('po').feature('sl1').set('linerelax', 0.7);
model.sol('sol1').feature('s1').feature('i1').feature('mg1').feature('po').feature('sl1').set('relax', 0.5);
model.sol('sol1').feature('s1').feature('i1').feature('mg1').feature('cs').label('Coarse Solver 1');
model.sol('sol1').feature('s1').feature('i1').feature('mg1').feature('cs').feature('dDef').label('Direct 2');
model.sol('sol1').feature('s1').feature('i1').feature('mg1').feature('cs').feature('d1').label('Direct 1.1');
model.sol('sol1').feature('s1').feature('i1').feature('mg1').feature('cs').feature('d1').set('linsolver', 'pardiso');
model.sol('sol1').feature('s1').feature('i1').feature('mg1').feature('cs').feature('d1').set('pivotperturb', 1.0E-13);
model.sol('sol1').feature('su1').label('Solution Store 1.1');
model.sol('sol1').feature('st2').active(true);
model.sol('sol1').feature('st2').label('Compile Equations: Time Dependent');
model.sol('sol1').feature('st2').set('studystep', 'time');
model.sol('sol1').feature('v2').label('Dependent Variables 2.1');
model.sol('sol1').feature('v2').set('resscalemethod', 'manual');
model.sol('sol1').feature('v2').set('clist', {'10^{range(log10(0.001),1/3,log10(10))}[ms]' '0.009999000000000001[ms]'});
model.sol('sol1').feature('t1').label('Time-Dependent Solver 1.1');
model.sol('sol1').feature('t1').set('control', 'time');
model.sol('sol1').feature('t1').set('tunit', 'ms');
model.sol('sol1').feature('t1').set('tlist', '10^{range(log10(0.001),1/3,log10(10))}');
model.sol('sol1').feature('t1').set('rtol', 0.005);
model.sol('sol1').feature('t1').set('maxorder', 2);
model.sol('sol1').feature('t1').set('stabcntrl', true);
model.sol('sol1').feature('t1').feature('dDef').label('Direct 2');
model.sol('sol1').feature('t1').feature('aDef').label('Advanced 1');
model.sol('sol1').feature('t1').feature('aDef').set('cachepattern', true);
model.sol('sol1').feature('t1').feature('fc1').label('Fully Coupled 1.1');
model.sol('sol1').feature('t1').feature('fc1').set('linsolver', 'd1');
model.sol('sol1').feature('t1').feature('fc1').set('maxiter', 8);
model.sol('sol1').feature('t1').feature('fc1').set('damp', '0.9');
model.sol('sol1').feature('t1').feature('fc1').set('jtech', 'once');
model.sol('sol1').feature('t1').feature('fc1').set('stabacc', 'aacc');
model.sol('sol1').feature('t1').feature('fc1').set('aaccdim', 5);
model.sol('sol1').feature('t1').feature('fc1').set('aaccmix', 0.9);
model.sol('sol1').feature('t1').feature('fc1').set('aaccdelay', 1);
model.sol('sol1').feature('t1').feature('d1').label('Direct, concentrations (tds)');
model.sol('sol1').feature('t1').feature('i1').label('AMG, concentrations (tds)');
model.sol('sol1').feature('t1').feature('i1').set('maxlinit', 50);
model.sol('sol1').feature('t1').feature('i1').feature('ilDef').label('Incomplete LU 1');
model.sol('sol1').feature('t1').feature('i1').feature('mg1').label('Multigrid 1.1');
model.sol('sol1').feature('t1').feature('i1').feature('mg1').set('prefun', 'saamg');
model.sol('sol1').feature('t1').feature('i1').feature('mg1').set('maxcoarsedof', 50000);
model.sol('sol1').feature('t1').feature('i1').feature('mg1').set('saamgcompwise', true);
model.sol('sol1').feature('t1').feature('i1').feature('mg1').set('usesmooth', false);
model.sol('sol1').feature('t1').feature('i1').feature('mg1').feature('pr').label('Presmoother 1');
model.sol('sol1').feature('t1').feature('i1').feature('mg1').feature('pr').feature('soDef').label('SOR 1');
model.sol('sol1').feature('t1').feature('i1').feature('mg1').feature('pr').feature('sl1').label('SOR Line 1.1');
model.sol('sol1').feature('t1').feature('i1').feature('mg1').feature('pr').feature('sl1').set('linesweeptype', 'ssor');
model.sol('sol1').feature('t1').feature('i1').feature('mg1').feature('pr').feature('sl1').set('iter', 1);
model.sol('sol1').feature('t1').feature('i1').feature('mg1').feature('pr').feature('sl1').set('linerelax', 0.7);
model.sol('sol1').feature('t1').feature('i1').feature('mg1').feature('pr').feature('sl1').set('relax', 0.5);
model.sol('sol1').feature('t1').feature('i1').feature('mg1').feature('po').label('Postsmoother 1');
model.sol('sol1').feature('t1').feature('i1').feature('mg1').feature('po').feature('soDef').label('SOR 1');
model.sol('sol1').feature('t1').feature('i1').feature('mg1').feature('po').feature('sl1').label('SOR Line 1.1');
model.sol('sol1').feature('t1').feature('i1').feature('mg1').feature('po').feature('sl1').set('linesweeptype', 'ssor');
model.sol('sol1').feature('t1').feature('i1').feature('mg1').feature('po').feature('sl1').set('iter', 1);
model.sol('sol1').feature('t1').feature('i1').feature('mg1').feature('po').feature('sl1').set('linerelax', 0.7);
model.sol('sol1').feature('t1').feature('i1').feature('mg1').feature('po').feature('sl1').set('relax', 0.5);
model.sol('sol1').feature('t1').feature('i1').feature('mg1').feature('cs').label('Coarse Solver 1');
model.sol('sol1').feature('t1').feature('i1').feature('mg1').feature('cs').feature('dDef').label('Direct 2');
model.sol('sol1').feature('t1').feature('i1').feature('mg1').feature('cs').feature('d1').label('Direct 1.1');
model.sol('sol1').feature('t1').feature('i1').feature('mg1').feature('cs').feature('d1').set('linsolver', 'pardiso');
model.sol('sol1').feature('t1').feature('i1').feature('mg1').feature('cs').feature('d1').set('pivotperturb', 1.0E-13);
model.sol('sol1').runAll;

model.result('pg1').label('Electric Potential (es)');
model.result('pg1').set('xlabel', 'Length (unit Debye lengths) (1)');
model.result('pg1').set('ylabel', 'Electric potential (V)');
model.result('pg1').set('ylabelactive', true);
model.result('pg1').set('xlabelactive', false);
model.result('pg1').feature('lngr1').set('xdataexpr', 'x/xD');
model.result('pg1').feature('lngr1').set('xdataunit', '1');
model.result('pg1').feature('lngr1').set('xdatadescractive', true);
model.result('pg1').feature('lngr1').set('xdatadescr', 'Length (unit Debye lengths)');
model.result('pg1').feature('lngr1').set('legend', true);
model.result('pg1').feature('lngr1').set('legendmethod', 'manual');
model.result('pg1').feature('lngr1').set('legends', {'Phi'});
model.result('pg1').feature('lngr1').set('resolution', 'normal');
model.result('pg1').feature('ptgr1').set('xdata', 'expr');
model.result('pg1').feature('ptgr1').set('xdataexpr', 'x/xD');
model.result('pg1').feature('ptgr1').set('xdataunit', '1');
model.result('pg1').feature('ptgr1').set('xdatadescractive', true);
model.result('pg1').feature('ptgr1').set('xdatadescr', 'Length (unit Debye lengths)');
model.result('pg1').feature('ptgr1').set('linestyle', 'none');
model.result('pg1').feature('ptgr1').set('linecolor', 'red');
model.result('pg1').feature('ptgr1').set('linewidth', 'preference');
model.result('pg1').feature('ptgr1').set('linemarker', 'point');
model.result('pg1').feature('ptgr1').set('markerpos', 'datapoints');
model.result('pg1').feature('ptgr1').set('legend', true);
model.result('pg1').feature('ptgr1').set('legendmethod', 'manual');
model.result('pg1').feature('ptgr1').set('legends', {'PhiM'});
model.result('pg2').label('Concentrations, All Species (tds)');
model.result('pg2').set('looplevelinput', {'last'});
model.result('pg2').set('titletype', 'none');
model.result('pg2').set('xlabel', 'Spatial coordinates, x-component (nm)');
model.result('pg2').set('ylabel', 'Concentration (mol/m<sup>3</sup>)');
model.result('pg2').set('xlabelactive', false);
model.result('pg2').set('ylabelactive', false);
model.result('pg2').feature('lngr1').label('Species A');
model.result('pg2').feature('lngr1').set('xdataexpr', 'x');
model.result('pg2').feature('lngr1').set('xdataunit', 'nm');
model.result('pg2').feature('lngr1').set('xdatadescr', 'Spatial coordinates, x-component');
model.result('pg2').feature('lngr1').set('legend', true);
model.result('pg2').feature('lngr1').set('legendmethod', 'manual');
model.result('pg2').feature('lngr1').set('legends', {'A<sup>+</sup> Concentration'});
model.result('pg2').feature('lngr1').set('resolution', 'normal');
model.result('pg2').feature('lngr2').label('Species X');
model.result('pg2').feature('lngr2').set('xdataexpr', 'x');
model.result('pg2').feature('lngr2').set('xdataunit', 'nm');
model.result('pg2').feature('lngr2').set('xdatadescr', 'Spatial coordinates, x-component');
model.result('pg2').feature('lngr2').set('legend', true);
model.result('pg2').feature('lngr2').set('legendmethod', 'manual');
model.result('pg2').feature('lngr2').set('legends', {'X<sup>-</sup> Concentration'});
model.result('pg2').feature('lngr2').set('resolution', 'normal');
model.result('pg3').label('Concentration, A (tds)');
model.result('pg3').set('titletype', 'custom');
model.result('pg3').set('prefixintitle', 'Species A:');
model.result('pg3').set('typeintitle', false);
model.result('pg3').set('xlabel', 'Spatial coordinates, x-component (m)');
model.result('pg3').set('ylabel', 'Concentration (mol/m<sup>3</sup>)');
model.result('pg3').set('legendlayout', 'outside');
model.result('pg3').set('xlabelactive', false);
model.result('pg3').set('ylabelactive', false);
model.result('pg3').feature('lngr1').set('xdataexpr', 'x');
model.result('pg3').feature('lngr1').set('xdataunit', 'm');
model.result('pg3').feature('lngr1').set('xdatadescr', 'Spatial coordinates, x-component');
model.result('pg3').feature('lngr1').set('linemarker', 'cycle');
model.result('pg3').feature('lngr1').set('markers', 1);
model.result('pg3').feature('lngr1').set('legend', true);
model.result('pg3').feature('lngr1').set('resolution', 'normal');
model.result('pg4').label('Concentration, X (tds)');
model.result('pg4').set('titletype', 'custom');
model.result('pg4').set('prefixintitle', 'Species X:');
model.result('pg4').set('typeintitle', false);
model.result('pg4').set('xlabel', 'Spatial coordinates, x-component (m)');
model.result('pg4').set('ylabel', 'Concentration (mol/m<sup>3</sup>)');
model.result('pg4').set('legendlayout', 'outside');
model.result('pg4').set('xlabelactive', false);
model.result('pg4').set('ylabelactive', false);
model.result('pg4').feature('lngr1').set('xdataexpr', 'x');
model.result('pg4').feature('lngr1').set('xdataunit', 'm');
model.result('pg4').feature('lngr1').set('xdatadescr', 'Spatial coordinates, x-component');
model.result('pg4').feature('lngr1').set('linemarker', 'cycle');
model.result('pg4').feature('lngr1').set('markers', 1);
model.result('pg4').feature('lngr1').set('legend', true);
model.result('pg4').feature('lngr1').set('resolution', 'normal');
model.result('pg5').label('Surface Charge Density');
model.result('pg5').set('titletype', 'none');
model.result('pg5').set('xlabel', 'Voltage of electrode vs PZC (V)');
model.result('pg5').set('ylabel', 'Charge density (C/m<sup>2</sup>)');
model.result('pg5').set('ylabelactive', true);
model.result('pg5').set('legendpos', 'lowerright');
model.result('pg5').set('xlabelactive', false);
model.result('pg5').feature('ptgr1').set('xdata', 'expr');
model.result('pg5').feature('ptgr1').set('xdataexpr', 'phiM');
model.result('pg5').feature('ptgr1').set('xdatadescr', 'Voltage of electrode vs PZC');
model.result('pg5').feature('ptgr1').set('linestyle', 'none');
model.result('pg5').feature('ptgr1').set('linewidth', 'preference');
model.result('pg5').feature('ptgr1').set('linemarker', 'circle');
model.result('pg5').feature('ptgr1').set('markerpos', 'datapoints');
model.result('pg5').feature('ptgr1').set('legend', true);
model.result('pg5').feature('ptgr1').set('legendmethod', 'manual');
model.result('pg5').feature('ptgr1').set('legends', {'Surface charge density (simulation)'});
model.result('pg5').feature('glob1').set('expr', {'Cd_GCS*phiM'});
model.result('pg5').feature('glob1').set('unit', {'C/m^2'});
model.result('pg5').feature('glob1').set('descr', {'Surface charge density (theory)'});
model.result('pg5').feature('glob1').set('xdata', 'expr');
model.result('pg5').feature('glob1').set('xdataexpr', 'phiM');
model.result('pg5').feature('glob1').set('xdataunit', 'V');
model.result('pg5').feature('glob1').set('xdatadescr', 'Voltage of electrode vs PZC');
model.result('pg5').feature('glob1').set('linewidth', 'preference');

out = model;
